### ISSUE TITLE
Pip backtracking on install

### ISSUE THREAD

**Issue by OmikronApex** [magenta/magenta#2005]
As of today pip starts backtracking versions of many packages when I try to install magenta in google colab.

Log excerpt:
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of promise to determine which version is compatible with other requirements. This could take a while.
Collecting promise
  Downloading promise-2.3.tar.gz (19 kB)
  Downloading promise-2.2.1.tar.gz (19 kB)
  Downloading promise-2.2.tar.gz (19 kB)
INFO: pip is looking at multiple versions of tensorflow-gan to determine which version is compatible with other requirements. This could take a while.
  Downloading promise-2.1.tar.gz (17 kB)
Collecting typing
  Downloading typing-3.7.4.3.tar.gz (78 kB)
     |████████████████████████████████| 78 kB 9.0 MB/s 
Collecting promise
  Downloading promise-2.0.2.tar.gz (18 kB)
  Downloading promise-2.0.1.tar.gz (18 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Downloading promise-2.0.tar.gz (18 kB)
INFO: pip is looking at multiple versions of promise to determine which version is compatible with other requirements. This could take a while.
  Downloading promise-1.0.1.tar.gz (7.8 kB)
  Downloading promise-1.0.0.tar.gz (7.8 kB)
  Downloading promise-0.4.3.tar.gz (7.4 kB)
  Downloading promise-0.4.2.tar.gz (7.3 kB)
  Downloading promise-0.4.1.tar.gz (6.9 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Downloading promise-0.4.tar.gz (6.8 kB)
  Downloading promise-0.2.2.tar.gz (19 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/13/ee/eb8413c7e46f2dc110454e366b3ccf39e6db765749c8daf01a625c33323f/promise-0.2.2.tar.gz#sha256=1fb52a23bee47644819c4a11b0b7169474625c44629f9b76a04cf59e118f4f6c (from https://pypi.org/simple/promise/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading promise-0.2.1.tar.gz (18 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/f6/07/fcd91d39d6f80c4c9a314efa28dbff33c91ef9aaf94169bcee09aa70d50f/promise-0.2.1.tar.gz#sha256=edbc51aa90318c9157f980b715e614543c863b86add41be70885c649cceef343 (from https://pypi.org/simple/promise/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading promise-0.2.0.tar.gz (17 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/96/22/7ab1480ca9de349c380a4fbdf1a1ebcbfe2adef5a6183a26a0a9d88b8c6c/promise-0.2.0.tar.gz#sha256=bd8c3ed58092547c19bf5d321a5a6eb574e8327ff7c9e7b30b463beb54f5cb84 (from https://pypi.org/simple/promise/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading promise-0.1.0.tar.gz (16 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/2c/be/f9e01d392107df0e35f88c1d3ca4d9994a84d962214fe155c72bebe1e851/promise-0.1.0.tar.gz#sha256=c2da3af5f1695077a8c130e5f05f308afae5030343925be2bdc9cffad995d678 (from https://pypi.org/simple/promise/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
INFO: pip is looking at multiple versions of importlib-resources to determine which version is compatible with other requirements. This could take a while.
Collecting importlib-resources
  Downloading importlib_resources-5.8.0-py3-none-any.whl (28 kB)

How can I resolve this? The install process wasn't finished after an hour where it used to take 2-3 minutes.

**Comment by keylightjaeyong** [comment]
Last week, it ran without any problem, but after changing magenta==2.1.0, an error occurs as shown below.
(https://colab.research.google.com/notebooks/magenta/piano_transformer/piano_transformer.ipynb#scrollTo=tciXVi5eWG_1)

%tensorflow_version 1.x

print('Copying Salamander piano SoundFont (via https://sites.google.com/site/soundfonts4u) from GCS...')
!gsutil -q -m cp -r gs://magentadata/models/music_transformer/primers/* /content/
!gsutil -q -m cp gs://magentadata/soundfonts/Yamaha-C5-Salamander-JNv5.1.sf2 /content/

print('Installing dependencies...')
!apt-get update -qq && apt-get install -qq libfluidsynth1 build-essential libasound2-dev libjack-dev
!pip install -q 'tensorflow-datasets < 4.0.0'
!pip install -qU google-cloud magenta==2.1.0 pyfluidsynth
print('Importing libraries...')

import numpy as np
import os
import tensorflow.compat.v1 as tf

from google.colab import files

from tensor2tensor import models
from tensor2tensor import problems
from tensor2tensor.data_generators import text_encoder
from tensor2tensor.utils import decoding
from tensor2tensor.utils import trainer_lib

from magenta.models.score2perf import score2perf
import note_seq

tf.disable_v2_behavior()

print('Done!')
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-52ffe6d503c9>](https://localhost:8080/#) in <module>()
     29 from tensor2tensor.utils import trainer_lib
     30 
---> 31 from magenta.models.score2perf import score2perf
     32 import note_seq
     33 

ModuleNotFoundError: No module named 'magenta.models.score2perf'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by OmikronApex** [comment]
Version 2.1.0 might be to old for the model you're using, it was just the first I tried and it worked for me. Maybe try 2.1.1 and see if it works

**Comment by keylightjaeyong** [comment]
Thanks u, 
I try to do !pip install -qU google-cloud magenta=2.1.1 pyfluidsynth
but I see the same issue:

Copying Salamander piano SoundFont (via https://sites.google.com/site/soundfonts4u) from GCS...
Installing dependencies...
ERROR: Invalid requirement: 'magenta=2.1.1'
Hint: = is not a valid operator. Did you mean == ?
Importing libraries...
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-7-eb6756f5be25>](https://localhost:8080/#) in <module>()
     29 from tensor2tensor.utils import trainer_lib
     30 
---> 31 from magenta.models.score2perf import score2perf
     32 import note_seq
     33 

ModuleNotFoundError: No module named 'magenta.models.score2perf'

**Comment by keylightjaeyong** [comment]
Thanks u,
I try to do !pip install -qU google-cloud magenta==2.1.0 pyfluidsynth

print('Installing dependencies...')
!apt-get update -qq && apt-get install -qq libfluidsynth1 build-essential libasound2-dev libjack-dev
!pip install -q 'tensorflow-datasets < 4.0.0'
!pip install -qU google-cloud magenta==2.1.0 pyfluidsynth

print('Importing libraries...')

import numpy as np
import os
import tensorflow.compat.v1 as tf

from google.colab import files

from tensor2tensor import models
from tensor2tensor import problems
from tensor2tensor.data_generators import text_encoder
from tensor2tensor.utils import decoding
from tensor2tensor.utils import trainer_lib

but I see the same issue:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-17-a22d2132865e>](https://localhost:8080/#) in <module>()
     23 from google.colab import files
     24 
---> 25 from tensor2tensor import models
     26 from tensor2tensor import problems
     27 from tensor2tensor.data_generators import text_encoder

6 frames
[/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py](https://localhost:8080/#) in make(id, max_episode_steps, autoreset, disable_env_checker, **kwargs)
    579             raise error.Error(f"No registered env with id: {id}")
    580 
--> 581     _kwargs = spec_.kwargs.copy()
    582     _kwargs.update(kwargs)
    583 

AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by f403** [comment]
Looks like latest `note-seq` is breaking dependencies.
Try downgrading with: `pip install note-seq==0.0.3 magenta`

Magenta has no pinned version of `note-seq` in its dependencies, 
as well as for a plenty of other packages, this can cause same issues any time in the future.

**Comment by p-ferreira** [comment]
I'm having the same problem on my side, and not only with collab but in other instances as well, such as installing magenta with `pip install magenta` , use their installation bash script and building the source code locally.

I was able to make it work with the insight of @f403 to downgrade note-seq. But in my end, I was only able to make it work using `note-seq===0.0.2`, version 0.0.3 didn't work for me.

**Downgrading note-seq command example:**

`pip install note-seq==0.0.2 magenta`

**Comment by keylightjaeyong** [comment]
I try to work your method (pip install note-seq==0.0.2 magenta)
(Generating Piano Music with Transformer.ipynb, https://colab.research.google.com/notebooks/magenta/piano_transformer/piano_transformer.ipynb#scrollTo=tciXVi5eWG_1)

but I have the same problem as below shown,
#@title Setup Environment
#@markdown Copy some auxiliary data from Google Cloud Storage.
#@markdown Also install and import Python dependencies needed
#@markdown for running the Transformer models.

%tensorflow_version 1.x

print('Copying Salamander piano SoundFont (via https://sites.google.com/site/soundfonts4u) from GCS...')
!gsutil -q -m cp -r gs://magentadata/models/music_transformer/primers/* /content/
!gsutil -q -m cp gs://magentadata/soundfonts/Yamaha-C5-Salamander-JNv5.1.sf2 /content/

print('Installing dependencies...')
!apt-get update -qq && apt-get install -qq libfluidsynth1 build-essential libasound2-dev libjack-dev
!pip install -q 'tensorflow-datasets < 4.0.0'
#!pip install -qU google-cloud magenta pyfluidsynth
!pip install note-seq==0.0.2 magenta
!pip install -qU google-cloud pyfluidsynth

print('Importing libraries...')

import numpy as np
import os
import tensorflow.compat.v1 as tf

from google.colab import files

from tensor2tensor import models
from tensor2tensor import problems
from tensor2tensor.data_generators import text_encoder
from tensor2tensor.utils import decoding
from tensor2tensor.utils import trainer_lib

from magenta.models.score2perf import score2perf
import note_seq

tf.disable_v2_behavior()

print('Done!')

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-5be00b904752>](https://localhost:8080/#) in <module>()
     31 from tensor2tensor.utils import trainer_lib
     32 
---> 33 from magenta.models.score2perf import score2perf
     34 import note_seq
     35 

ModuleNotFoundError: No module named 'magenta.models.score2perf'

**Comment by p-ferreira** [comment]
Indeed, I just tested your code  on my side and I had the same issue as you

I believe that maybe because note-seq is being manually set to an older version, pip will resolve magenta with an older version as well, one that does not have the `score2perf` module.

One way that I found to work around that is to use the `-U`  flag on the `pip install` command, where `-U` will [upgrade magenta to the newest version](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-U), which have the `score2perf` module.

You can either add the `note-seq==0.0.2` before magenta in the already existing command, like:

```python
!pip install -qU google-cloud note-seq==0.0.2 magenta pyfluidsynth
```

Or add the `-U` flag to the command that you added:

```python
!pip install -U note-seq==0.0.2 magenta
```

Side note, this type of dependency problem is real cumbersome to troubleshoot, which consequently complicates the access of this type of resource to the community. I hope magenta team fix this dependency issue soon so we don't have more problems with it

**Comment by leranjun** [comment]
I can reproduce. Using `note-seq==0.0.2` fixed the backtracking error for me, although I still can't install with Python 3.10 on Windows (seems like it's trying to build numba 0.48 and failed…)

**Comment by p-ferreira** [comment]
I see. I believe that maybe python 3.10 may conflict with other libraries. I set my versions accordingly to collab and deployed the whole thing as a conda environment. 

If you have conda, you might be able to make it work on your machine with the following command:

`conda env create -f magenta.yml`

env_file.yml:
```yml
name: magenta
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - jupyter
  - pip
  - pip:
    - numpy==1.19
    - tensorflow==1.15.2
    - note-seq==0.0.2
    - tensorflow-datasets==3.2.1
    - magenta
```

**Comment by leranjun** [comment]
> I can reproduce. Using `note-seq==0.0.2` fixed the backtracking error for me, although I still can't install with Python 3.10 on Windows (seems like it's trying to build numba 0.48 and failed…)

Managed to install successfully on Windows with Python 3.8, VC++ build tools and `note-seq==0.0.3 magenta`.

**Comment by IngoOutgo** [comment]
I'm having the same problem. I'm using the official nvidia cuda docker image (tried both 18.04 and 20.04). I also tried the magenta install script. None worked.

````
FROM nvidia/cuda:11.7.0-runtime-ubuntu18.04
SHELL ["/bin/bash", "-c"]

# Install base utilities
RUN apt-get update && \
    apt-get install -y libfluidsynth1 && \
    apt-get install -y build-essential && \
    apt-get install -y wget &&\
    apt-get install -y git &&\
    apt-get install -y fluid-soundfont-gm && \
    apt-get install -y libasound2-dev && \
    apt-get install -y libjack-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH
RUN conda init bash

RUN pip install magenta```
